{% set name = "stim" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumlib/Stim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3d606e8ae61bc8a3b40af2aa5ee88a2d4793c38d0d89472195fff069792e5233

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation --ignore-installed"
  skip: true # [py<310 or py>310]

requirements:
  host:
    - python >=3.10,<3.11
    - pip
    - pybind11
    - {{ compiler('cxx') }}
  run:
    - python >=3.10,<3.12
      #    - python_abi 3.10.* *_cp310
    - python_abi >=3.10
    - pybind11
    - numpy

test:
  imports:
    - stim

about:
  home: https://github.com/quantumlib/stim
  license: Apache-2.0
  summary: "A fast simulator for quantum stabilizer circuits."

extra:
  recipe-maintainers:
    - kmart-dev

