{% set name = "quantumlib-stim" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/quantumlib/Stim/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3d606e8ae61bc8a3b40af2aa5ee88a2d4793c38d0d89472195fff069792e5233
  - path: ./build-quantumlib-stim.py
  - path: ./test.py

build:
  number: 0

outputs:

  - name: quantumlib-stim
    build:
      script: python ./build-quantumlib-stim.py
      skip: true  # [py<310 or py>310]
      missing_dso_whitelist:
        - '*/libm.so.6'
        - '*/libc.so.6'
        - '*/libpthread.so.0'
        - '*/ld-linux-x86-64.so.2'
    requirements:
      host:
        - python 
        - pip
        - pybind11
        - numpy
        - conda-verify
        - {{ compiler('cxx') }}
      run:
        - python
        - python_abi 3.10.* *_cp310
        - pybind11
        - numpy
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - quantumlib_stim
      source_files:
        - test.py
      commands:
        - python test.py
      requires: 
        - pytest

  - name: quantumlib-stimcirq
    build:
      script: "python -m pip install ./glue/cirq --no-deps --ignore-installed --no-build-isolation --ignore-installed"
      skip: true  # [py<310 or py>310 or osx]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - python_abi 3.10.* *_cp310
        - quantumlib-stim # depends on main stim package
        - cirq
    test:
      imports:
        - quantumlib_stimcirq
#      commands:
#        - python -c "import quantumlib_stimcirq; print(quantumlib_stimcirq.__doc__)"

about:
  home: https://github.com/quantumlib/stim
  license: Apache-2.0
  summary: "A fast simulator for quantum stabilizer circuits."

extra:
  recipe-maintainers:
    - kmart-dev

