# conda-forge.yml

recipe_dir: recipe
clone_depth: 0

provider:
  linux: github_actions
  win: github_actions
  osx: github_actions

build_platform:
  linux_64: linux_64
  win_64: win_64
  osx_64: osx_64
  # Enable this when ready to cross-compile for Apple Silicon:
  # osx_arm64: osx_arm64

github_actions:
  self_hosted: false

# Replaces deprecated test_on_native_only: true
test: native_and_emulated

github:
  user_or_org: kmart-dev
  repo_name: stim-feedstock

bot:
  automerge: false

# Reduce unnecessary rendering
skip_render:
  - README.md
  - LICENSE.txt
  - .gitignore
  - .gitattributes
  - build-locally.py
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md

