provider:
  linux: azure  # Use CircleCI for Linux builds (if necessary; GitHub Actions is preferred now)
  win: azure     # Use Cirun for Windows builds (you must opt into this manually)

build_platform:
  linux_64: linux_64

clone_depth: 0
recipe_dir: recipe

# Don't use build_with_mambar, because not supported in conda-forge.yml
# build_with_mamba: true

skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - build-locally.py
  - LICENSE
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
