{% set version = "1.15.0" %}

package:
  name: stim-meta
  version: {{ version }}

source:
  - url: https://github.com/quantumlib/Stim/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3d606e8ae61bc8a3b40af2aa5ee88a2d4793c38d0d89472195fff069792e5233
  - path: ./build-stim.sh
  - path: ./test.py

build:
  number: 0

outputs:

  - name: stim
    build:
      script: ./build-stim.sh
      skip: true  # [py<310 or py>310 or osx]
      missing_dso_whitelist:
        - '*/libm.so.6'
        - '*/libc.so.6'
        - '*/libpthread.so.0'
        - '*/ld-linux-x86-64.so.2'
    requirements:
      host:
        - python
        - pip
        - pybind11
        - conda-verify
        - {{ compiler('cxx') }}
      run:
        - python
        - python_abi 3.10.* *_cp310
        - pybind11
        - numpy
        - conda-verify
    test:
      imports:
        - stim
      source_files:
        - test.py
      commands:
        - python test.py
    about:
      home: https://github.com/quantumlib/stim
      license: Apache-2.0
      summary: "A fast simulator for quantum stabilizer circuits."

  - name: sinter
    build:
      script: ./build-stim.sh
      skip: true  # [py<310 or py>310 or osx]
    requirements:
      host:
        - python
        - pip
        - pybind11
        - conda-verify
        - {{ compiler('cxx') }}
      run:
        - python
        - python_abi 3.10.* *_cp310
        - pybind11
        - numpy
        - stim
        - conda-verify
    test:
      imports:
        - sinter
    about:
      home: https://github.com/quantumlib/stim
      license: Apache-2.0
      summary: "Benchmarking utility for stim, written in Python."

  - name: stimcirq
    build:
      script: ./build-stim.sh
      skip: true  # [py<310 or py>310 or osx]
    requirements:
      host:
        - python
        - pip
        - pybind11
        - conda-verify
        - {{ compiler('cxx') }}
      run:
        - python
        - python_abi 3.10.* *_cp310
        - pybind11
        - numpy
        - stim
        - conda-verify
        - cirq-core  # Adjust if pip install uses a different cirq name
    test:
      imports:
        - stimcirq
    about:
      home: https://github.com/quantumlib/stim
      license: Apache-2.0
      summary: "Cirq integration package for stim."

extra:
  recipe-maintainers:
    - kmart-dev

