version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Conda & Dependencies
          command: |
            sudo apt update
            sudo apt install -y libboost-all-dev
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
      - run:
          name: Verify Conda Installation
          command: conda --version
      - run:
          name: Set Up Conda Environment
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda create -n build-env python=3.9 -y
            conda activate build-env
      - run:
          name: Build Stim Package
          command: conda build recipe/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

