version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use Python image (or adjust for your package)
    steps:
      - checkout
      - run:
          name: Install Conda & Dependencies
          command: |
            sudo apt update
            sudo apt install -y libboost-all-dev  # Adjust dependencies as needed
            curl -L https://github.com/conda/conda/releases/latest/download/conda.sh | bash
      - run:
          name: Set Up Conda Environment
          command: |
            conda create -n build-env python=3.9
            conda activate build-env
      - run:
          name: Build Stim Package
          command: conda build recipe/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

