version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10  # Using Python 3.10 to match Conda recipe requirements
    steps:
      - checkout

      - run:
          name: Install Conda & Dependencies
          command: |
            sudo apt update
            sudo apt install -y libboost-all-dev
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> ~/.bashrc
            source ~/.bashrc
            echo "PATH after Miniconda install: $PATH"
            conda config --add channels conda-forge
            conda config --set channel_priority strict

      - run:
          name: Verify Conda Installation
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            export PATH="$HOME/miniconda/bin:$PATH"
            echo "PATH: $PATH"
            conda --version
            which conda
            conda info

      - run:
          name: Create & Activate Conda Environment
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda create --name build_env python=3.10 -y
            echo "Available environments:"
            conda info --envs
            conda activate build_env
            echo "Python version inside Conda environment:"
            python --version
            which python

      - run:
          name: Install `conda-build`
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda activate build_env
            conda install -c conda-forge conda-build -y
            conda info --envs  # Verify environment setup
            conda list | grep conda-build  # Confirm conda-build installation

      - run:
          name: Build Stim Package
          command: |
            source $HOME/miniconda/etc/profile.d/conda.sh
            conda activate build_env
            conda build recipe/
            echo "Checking Conda output directory:"
            ls -lh $HOME/miniconda/conda-bld/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

