# Recipe-specific conda build configuration for quantumlib-stimcirq
# This overrides or extends the global configuration

# stimcirq is pure Python, so simpler build requirements
build_string_pattern: "py{py}_{PKG_BUILDNUM}"

# Additional skip conditions for stimcirq
skip:
  - py<310 or py>310
  - osx  # Skip macOS entirely if cirq has issues there

# Cirq version pinning (if needed)
cirq:
  - ">=1.0.0"

# Test requirements for stimcirq
test_requires:
  - pytest
  - cirq
