{% set name = "quantumlib-stimcirq" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumlib/Stim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3d606e8ae61bc8a3b40af2aa5ee88a2d4793c38d0d89472195fff069792e5233

build:
  number: 0
  script: "python -m pip install ./glue/cirq --no-deps --ignore-installed --no-build-isolation"
#  skip: true  # [py<310 or py>310 or osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python_abi {{ python }} *_cp{{ python.replace('.', '') }}
    - quantumlib-stim  # This is the key dependency!
    - cirq

test:
  imports:
    - stimcirq
  commands:
    - python -c "import stimcirq; print('stimcirq imported successfully')"
    - python -c "import quantumlib_stim; import stimcirq; print('Both packages work together')"
    - echo "🎉 Conda tests for quantumlib-stimcirq passed successfully! 🎉"

about:
  home: https://github.com/quantumlib/stim
  license: Apache-2.0
  summary: "Cirq integration for the Stim quantum stabilizer circuit simulator."

extra:
  recipe-maintainers:
    - kmart-dev
