# Recipe-specific conda build configuration for quantumlib-stim
# This overrides or extends the global configuration

# Specific build requirements for stim (C++ intensive package)
cxx_compiler_version:
  - 9     # [linux]
  - 11    # [osx]
  - 14.2  # [win]

# Stim-specific build flags
build_string_pattern: "h{PKG_HASH}_{PKG_BUILDNUM}"

# Additional skip conditions specific to stim
# (combines with global skip conditions)
skip:
  - py<310 or py>310
  - osx and x86_64  # Skip Intel Mac if desired

# Stim requires specific numpy version for C++ bindings
numpy:
  - "1.22.*"

# Test requirements specific to stim
test_requires:
  - pytest
  - pytest-xdist
  - numpy

# Define preferred channels
#channels:
#  - conda-forge
