{% set name = "quantumlib-stim" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/quantumlib/Stim/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3d606e8ae61bc8a3b40af2aa5ee88a2d4793c38d0d89472195fff069792e5233

build:
  number: 0
# - path: ./build-quantumlib-stim.py
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310 or py>310]
  missing_dso_whitelist:
    - '*/libm.so.6'
    - '*/libc.so.6'
    - '*/libpthread.so.0'
    - '*/ld-linux-x86-64.so.2'

requirements:
  host:
    - python
    - pip
    - pybind11
    - numpy
    - conda-verify
    - {{ compiler('cxx') }}
    - {{ stdlib('cxx') }}
  run:
    - python
    - python_abi 3.10.* *_cp310
    - pybind11
    - numpy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    # - quantumlib_stim
    - stim
  requires:
    - pytest
  commands:
    # This command will only execute if all preceding 'imports' were successful.
    - echo "🎉 Conda tests for quantumlib-stim passed successfully! 🎉"

about:
  home: https://github.com/quantumlib/stim
  license: Apache-2.0
  summary: "A fast simulator for quantum stabilizer circuits."

extra:
  recipe-maintainers:
    - kmart-dev
