# .github/workflows/build.yml

name: build-conda-packages

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} w/ Py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
        include:
          - os: macos-latest
            target-platform: osx-64
          - os: ubuntu-latest
            target-platform: linux-64
          - os: windows-latest
            target-platform: win-64
    env:
      CONDA_BLD_PATH: ./build_artifacts

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          activate-environment: build-env

      - name: Install conda-build and mamba
        shell: bash -l {0}
        run: |
          conda create -n build-env -c conda-forge python=${{ matrix.python-version }} conda-build mamba pybind11 --yes
          conda activate build-env

      - name: Configure CONDA_SUBDIR (Apple Silicon only)
        if: matrix.target-platform == 'osx-arm64'
        shell: bash -l {0}
        run: echo "CONDA_SUBDIR=osx-arm64" >> $GITHUB_ENV

      # Optional: Enable this for faster rebuilds after things stabilize
      # - name: Cache conda build folder
      #   uses: actions/cache@v3
      #   with:
      #     path: ./build_artifacts
      #     key: conda-build-${{ matrix.os }}-${{ matrix.python-version }}
      - name: Build package
        shell: bash -l {0}
        run: |
          echo "Building for platform: ${{ matrix.target-platform }} with Python ${{ matrix.python-version }}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            call "%CONDA%\\condabin\\conda.bat" activate build-env
          else
            source "$(conda info --base)/etc/profile.d/conda.sh"
            conda activate build-env
          fi
          conda build ${{ github.workspace }}/recipe \
            -c conda-forge \
            --output-folder $CONDA_BLD_PATH \
      --python ${{ matrix.python-version }}
