name: build-conda-packages
on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11"]
        include:
          - os: macos-latest
            target-platform: osx-64
          - os: ubuntu-latest
            target-platform: linux-64
          - os: windows-latest
            target-platform: win-64
    env:
      CONDA_BLD_PATH: ./build_artifacts

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict

      - name: Install conda-build and mamba
        #run: conda install -n base -c conda-forge conda-build mamba
        run: conda install -n base -c conda-forge conda-build=3.26 mamba=1.5

      - name: Configure CONDA_SUBDIR (Apple Silicon only)
        if: matrix.os == 'macos-latest'
        run: echo "CONDA_SUBDIR=osx-arm64" >> $GITHUB_ENV

      - name: Cache conda build folder
        uses: actions/cache@v3
        with:
          path: ./build_artifacts
          key: conda-build-${{ matrix.os }}-${{ matrix.python-version }}

      - name: Build package
        run: |
          echo "Building for platform: ${{ matrix.target-platform }} with Python ${{ matrix.python-version }}"
          conda mambabuild ${{ github.workspace }}/recipe -c conda-forge --python ${{ matrix.python-version }}

