name: Debug Cross-Platform Conda Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Print matrix variables
        run: |
          echo "Matrix OS: ${{ matrix.os }}"
          echo "Matrix Python: ${{ matrix.python-version }}"

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: build
          auto-activate-base: false
          auto-update-conda: true

      - name: Print PATH and env
        run: |
          echo ">> PATH"
          echo "$PATH"
          echo ">> ENV"
          env

      - name: Verify conda init
        run: |
          echo ">> Which conda"
          which conda
          echo ">> Conda version"
          conda --version
          echo ">> Conda env list"
          conda env list
          echo ">> Active environment"
          conda info --envs

      - name: Show conda config and version info
        run: |
          conda config --show
          conda info
          echo ">> Python version in PATH"
          python --version
          which python

      - name: Check pre-installed packages
        run: |
          echo ">> conda list before install"
          conda list

      - name: Configure conda-forge and install build tools
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install -y numpy=1.22 conda-build boa mamba
          echo ">> conda list after install"
          conda list

      - name: Build package with mamba
        run: |
          echo ">> conda build output path"
          conda build recipe --output
          echo ">> mambabuild"
          conda mambabuild recipe

      - name: Test built package
        run: |
          echo ">> Testing built package"
          conda build --test $(conda build recipe --output)

