name: Cross-Platform Conda Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: build
          auto-activate-base: false
          auto-update-conda: true

      - name: Configure conda-forge and install build tools
        shell: bash
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install -y numpy=1.22 conda-build boa mamba

      - name: Build package
        shell: bash
        run: |
          conda mambabuild recipe

      - name: Test package
        shell: bash
        run: |
          conda build --test $(conda build recipe --output)
B
B
B
B
B
B

