# .github/workflows/linux_build.yml
name: Linux Build

on:
  push:
  pull_request:

jobs:
  build-linux-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: build
          environment-file: environment.yml
          python-version: 3.10

      - name: Install dependencies
        run: |
          conda install -y conda-build boa
          conda install -y mamba -c conda-forge

      - name: Build feedstock
        run: |
          conda mambabuild recipe

      - name: Test built package
        run: |
          conda build --test $(conda build recipe --output)

