name: macOS Build

on:
  push:
  pull_request:

jobs:
  build-macos-64:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Miniconda manually
        run: |
          curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash

      - name: Setup environment
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda create -y -n build python=${{ matrix.python-version }}
          conda activate build
          conda install -y numpy=1.22 conda-build boa mamba -c conda-forge

      - name: Build
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate build
          conda mambabuild recipe

      - name: Test
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate build
          conda build --test $(conda build recipe --output)

