name: Windows Build

on:
  push:
  pull_request:

jobs:
  build-win-64:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Miniconda manually
        shell: powershell
        run: |
          Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile miniconda.exe
          Start-Process -Wait -FilePath .\miniconda.exe -ArgumentList "/InstallationType=JustMe", "/AddToPath=1", "/RegisterPython=0", "/S", "/D=$env:USERPROFILE\miniconda3"
          echo "$env:USERPROFILE\miniconda3\Scripts" | Out-File -Append -Encoding ASCII $env:GITHUB_PATH

      - name: Setup environment
        shell: powershell
        run: |
          & "$env:USERPROFILE\miniconda3\Scripts\conda.exe" create -y -n build python=${{ matrix.python-version }}
          & "$env:USERPROFILE\miniconda3\Scripts\activate" build
          & "$env:USERPROFILE\miniconda3\Scripts\conda.exe" install -y numpy=1.22 conda-build boa mamba -c conda-forge

      - name: Build
        shell: powershell
        run: |
          & "$env:USERPROFILE\miniconda3\Scripts\activate" build
          conda mambabuild recipe

      - name: Test
        shell: powershell
        run: |
          & "$env:USERPROFILE\miniconda3\Scripts\activate" build
          conda build --test (conda build recipe --output)

